version: "3.7"

services:
  db:
    restart: 'unless-stopped'
    image: mysql:5.7
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-storage:/var/lib/mysql
  redis:
    restart: 'unless-stopped'
    image: redis:6.2
    ports:
      - 6380:6379
  api:
    restart: 'unless-stopped'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started

volumes:
  db-storage:
